import './globals.css'
import '@/public/styles/style.css'
import {Montserrat } from 'next/font/google'
import "@fortawesome/fontawesome-svg-core/styles.css"; 

import { config } from "@fortawesome/fontawesome-svg-core";
import Header from '@/components/Header';
import Footer from '@/components/Footer';
config.autoAddCss = false; 

const monserrat = Montserrat({
  subsets: ['latin'],
  weight : '400'
})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body>{<Header />}{children}{<Footer/>}</body>
    </html>
  )
}
